branches:
  only:
    - master

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  # install setup.py's dependencies and dev requirements
  - pip install -e . -r requirements-dev.txt

script:
  - pytest
  - prospector

sudo: false

cache: pip
